
const ACTION_TYPES = {
    
    POST_USER_REQUEST: 'POST_USER_REQUEST',
    POST_USER_SUCCESS: 'POST_USER_SUCCESS',
    POST_USER_ERROR: 'POST_USER_ERROR',

    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_ERROR: 'GET_USERS_ERROR',


    POST_TASK_REQUEST: 'POST_TASK_REQUEST',
    POST_TASK_SUCCESS: 'POST_TASK_SUCCESS',
    POST_TASK_ERROR: 'POST_TASK_ERROR'

    }

export default ACTION_TYPES