
const ACTION_TYPES = {
    
    POST_USER_REQUEST: 'POST_USER_REQUEST',
    POST_USER_SUCCESS: 'POST_USER_SUCCESS',
    POST_USER_ERROR: 'POST_USER_ERROR',

    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_ERROR: 'GET_USERS_ERROR',


    POST_TASK_REQUEST: 'POST_TASK_REQUEST',
    POST_TASK_SUCCESS: 'POST_TASK_SUCCESS',
    POST_TASK_ERROR: 'POST_TASK_ERROR',

    GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
    GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
    GET_TASKS_ERROR: 'GET_TASKS_ERROR',

    PATCH_TASK_REQUEST: 'PATCH_TASK_REQUEST',
    PATCH_TASK_SUCCESS: 'PATCH_TASK_SUCCESS',
    PATCH_TASK_ERROR: 'PATCH_TASK_ERROR',

    DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_ERROR: 'DELETE_TASK_ERROR'

    }

export default ACTION_TYPES